name: linter

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: make lint
        env:
          CI: true